### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xbsdsongnan** [zwq2018/Data-Copilot#25]
Expecting value: line 1 column 1 (char 0),界面输入key出错

**Comment by xbsdsongnan** [comment]
本地跑，输入openai的key,然后就出错，要么就是一直演示延时不出图

**Comment by zwq2018** [comment]
报错是什么  你的key能正常用么   依赖都装好了么，听上去像个小问题

**Comment by xbsdsongnan** [comment]
Traceback (most recent call last):
  File "F:/WeGameApps/Data-Copilot-main/Data-Copilot-main/[main.py](http://main.py/)", line 388, in <module>
    output, image, df , output_result = run(instruction,
  File "F:/WeGameApps/Data-Copilot-main/Data-Copilot-main/[main.py](http://main.py/)", line 283, in run
    Previous_result[rename] = result_buffer[output_name][1]
KeyError: 'result1'

**Comment by zwq2018** [comment]
tushare可以直接用，或者写在环境变量里
