### ISSUE TITLE
本地方式启动解码报错

### ISSUE THREAD

**Issue by Fang-Joker** [zwq2018/Data-Copilot#41]
本地启动python main.py，报下面的gbk解码错误，请问这个是为什么？
检查了下系统是utf-8的编码方式的
(venv) PS D:\Tools\PyCharm 2023.2\project\Data-Copilot-main> python main.py
None
None
===============================Intent Detecting===========================================
Traceback (most recent call last):
  File "D:\Tools\PyCharm 2023.2\project\Data-Copilot-main\main.py", line 382, in <module>
    output, image, df , output_result = run(instruction, send_chat_request_Azure = openai_call, openai_key=openai_key, api_base='', engine='')
  File "D:\Tools\PyCharm 2023.2\project\Data-Copilot-main\main.py", line 128, in run
    prompt_task_dict = json.load(f)
  File "D:\refer-self\study-self\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),

**Comment by zwq2018** [comment]
with open(filename, 'r', encoding='utf-8') as f:
    prompt_task_dict = json.load(f)

你明确指定下编码方法试试吧 ，很容易debug

**Comment by Fang-Joker** [comment]
多谢，已解决
这边还有个问题。pro设置如下
openai_call = send_official_call
也购买了一个临时的openai的key
但是在main的Step-1:Task selec这个阶段的
response = send_chat_request_Azure(prompt_intent_detection, openai_key=openai_key, api_base=api_base, engine=engine)
一直报超时失败，我看lan_gpt4_call.py中send_official_call中确实是调用openai的请求，这种是因为key的问题导致的吗？我看我这边是能正常访问openai的官网的

**Comment by zwq2018** [comment]
我用的是微软云的openai，你要用openai官网的api稍微改下接口就可以
